server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    location /api/ {
        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /collector/ {
        rewrite ^/collector(/.*)$ $1 break;
        proxy_pass http://log-collector:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /detector/ {
        rewrite ^/detector(/.*)$ $1 break;
        proxy_pass http://detection-engine:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /explainer/ {
        rewrite ^/explainer(/.*)$ $1 break;
        proxy_pass http://explainer:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
